import Head from 'next/head'
import { Inter } from '@next/font/google'
import Button from '@/components/atoms/Button'
import { ComponentType } from "@/Enums/componentType"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Lars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      <Button model={{text:"test 1", link:"/", type: ComponentType.Primary }} />
      <Button model={{text:"test 2", link:"/", type: ComponentType.Secondary }} />
      </main>
    </>
  )
}
